file:
  service:
    getFileList:
      V1.0: {"bean":"fileServiceImpl","method":"getFileList"}
    getFileContent:
      V1.0: {"bean":"fileServiceImpl","method":"getFileContent"}
    modifyFile:
      V1.0: {"bean":"fileServiceImpl","method":"modifyFile"}